name: 'Bicep Deploy'

on:
  push:
    branches:
      - main

jobs:
  bicep:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true

      - name: Get SSH public key from Key Vault
        id: sshkey
        run: |
          echo "SSH_KEY=$(az keyvault secret show --name sshpublickey --vault-name keyvault-kv-cloud23 --query value -o tsv)" >> $GITHUB_ENV

      - name: Deploy Bicep template
        run: |
          az deployment group create \
            --resource-group bicep-test-rg \
            --template-file main.bicep \
            --parameters sshPublicKey="$SSH_KEY"
